using System;
using System.IO;
using System.Reflection;
using UnityEngine;
using UnityEditor;
using GaussianSplatting.Editor; // Namespace for GaussianSplatAssetCreator

public class AssetBundlePackager
{
    [MenuItem("3DGS/Pack Splat Asset")]
    public static void PackSplatAsset()
    {
        Debug.Log("[AssetBundlePackager] Starting batch AssetBundle build...");

        // Parse command line arguments
        string plyPath = GetArg("-plyPath");
        string assetName = GetArg("-assetName");
        string outputDir = GetArg("-outputDir");

        if (string.IsNullOrEmpty(plyPath) || string.IsNullOrEmpty(assetName) || string.IsNullOrEmpty(outputDir))
        {
            Debug.LogError("[AssetBundlePackager] Missing arguments! Required: -plyPath <path> -assetName <name> -outputDir <path>");
            EditorApplication.Exit(1);
            return;
        }

        try
        {
            // 1. Create GaussianSplatAssetCreator instance
            var creator = ScriptableObject.CreateInstance<GaussianSplatAssetCreator>();
            if (creator == null)
            {
                Debug.LogError("[AssetBundlePackager] Failed to instantiate GaussianSplatAssetCreator.");
                EditorApplication.Exit(1);
                return;
            }

            // 2. Set private fields using Reflection
            Type type = creator.GetType();
            type.GetField("m_InputFile", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(creator, plyPath);
            type.GetField("m_OutputFolder", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(creator, "Assets/GaussianAssets");

            // Set low quality to keep AssetBundle download size small for mobile
            // 0 = low, 1 = medium, 2 = high (corresponds to DataQuality enum)
            type.GetField("m_Quality", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(creator, 0); 

            // 3. Load the Input PLY File
            var loadMethod = type.GetMethod("LoadInputSplatFile", BindingFlags.NonPublic | BindingFlags.Instance);
            bool loaded = (bool)loadMethod.Invoke(creator, new object[] { plyPath });
            if (!loaded)
            {
                Debug.LogError($"[AssetBundlePackager] Failed to load PLY splat file: {plyPath}");
                EditorApplication.Exit(1);
                return;
            }

            // 4. Create the GaussianSplatAsset
            Debug.Log("[AssetBundlePackager] Compressing and generating GaussianSplatAsset...");
            var createMethod = type.GetMethod("CreateAsset", BindingFlags.NonPublic | BindingFlags.Instance);
            createMethod.Invoke(creator, null);

            // Destroy the creator window instance
            UnityEngine.Object.DestroyImmediate(creator);

            // 5. Refresh database to register the new files
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);

            string assetPath = $"Assets/GaussianAssets/{assetName}.asset";
            GaussianSplatting.Runtime.GaussianSplatAsset asset = AssetDatabase.LoadAssetAtPath<GaussianSplatting.Runtime.GaussianSplatAsset>(assetPath);
            if (asset == null)
            {
                Debug.LogError($"[AssetBundlePackager] Failed to load generated asset at {assetPath}");
                EditorApplication.Exit(1);
                return;
            }

            Debug.Log($"[AssetBundlePackager] Generated asset '{asset.name}' loaded successfully.");

            // 6. Assign the newly created asset to the AssetBundle
            AssetImporter importer = AssetImporter.GetAtPath(assetPath);
            importer.SetAssetBundleNameAndVariant("splat_bundle", "");

            // Also mark the generated bytes files for the same bundle
            string[] bytesFiles = Directory.GetFiles("Assets/GaussianAssets", $"{assetName}_*.bytes");
            foreach (var bytesPath in bytesFiles)
            {
                AssetImporter bytesImporter = AssetImporter.GetAtPath(bytesPath);
                if (bytesImporter != null)
                {
                    bytesImporter.SetAssetBundleNameAndVariant("splat_bundle", "");
                }
            }

            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);

            // 7. Ensure output directory exists
            if (!Directory.Exists(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // 8. Build the AssetBundle specifically for Android
            Debug.Log($"[AssetBundlePackager] Building Android AssetBundle in: {outputDir}");
            BuildPipeline.BuildAssetBundles(
                outputDir, 
                BuildAssetBundleOptions.None, 
                BuildTarget.Android
            );

            // 9. Clean up asset bundle names to keep project clean
            importer.SetAssetBundleNameAndVariant("", "");
            foreach (var bytesPath in bytesFiles)
            {
                AssetImporter bytesImporter = AssetImporter.GetAtPath(bytesPath);
                if (bytesImporter != null) bytesImporter.SetAssetBundleNameAndVariant("", "");
            }

            Debug.Log("[AssetBundlePackager] Batch AssetBundle build completed successfully!");
            EditorApplication.Exit(0);
        }
        catch (Exception ex)
        {
            Debug.LogError($"[AssetBundlePackager] Exception during build: {ex}");
            EditorApplication.Exit(1);
        }
    }

    private static string GetArg(string name)
    {
        string[] args = Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length; i++)
        {
            if (args[i] == name && i + 1 < args.Length)
            {
                return args[i + 1];
            }
        }
        return null;
    }
}
